// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	aiprovider3 "novels_ai_gen/internal/api/handler/aiprovider"
	auth2 "novels_ai_gen/internal/api/handler/auth"
	chapter3 "novels_ai_gen/internal/api/handler/chapter"
	character3 "novels_ai_gen/internal/api/handler/character"
	config2 "novels_ai_gen/internal/api/handler/config"
	event3 "novels_ai_gen/internal/api/handler/event"
	"novels_ai_gen/internal/api/handler/log"
	novel3 "novels_ai_gen/internal/api/handler/novel"
	novelagent3 "novels_ai_gen/internal/api/handler/novelagent"
	novelsummary3 "novels_ai_gen/internal/api/handler/novelsummary"
	prompt3 "novels_ai_gen/internal/api/handler/prompt"
	relationship3 "novels_ai_gen/internal/api/handler/relationship"
	system2 "novels_ai_gen/internal/api/handler/system"
	upload2 "novels_ai_gen/internal/api/handler/upload"
	"novels_ai_gen/internal/api/router"
	aiprovider2 "novels_ai_gen/internal/biz/aiprovider"
	"novels_ai_gen/internal/biz/auth"
	chapter2 "novels_ai_gen/internal/biz/chapter"
	character2 "novels_ai_gen/internal/biz/character"
	event2 "novels_ai_gen/internal/biz/event"
	novel2 "novels_ai_gen/internal/biz/novel"
	"novels_ai_gen/internal/biz/novelagent"
	novelsummary2 "novels_ai_gen/internal/biz/novelsummary"
	prompt2 "novels_ai_gen/internal/biz/prompt"
	relationship2 "novels_ai_gen/internal/biz/relationship"
	"novels_ai_gen/internal/biz/system"
	"novels_ai_gen/internal/biz/upload"
	"novels_ai_gen/internal/bootstrap/config"
	"novels_ai_gen/internal/bootstrap/db"
	"novels_ai_gen/internal/bootstrap/logger"
	"novels_ai_gen/internal/data/aiprovider"
	"novels_ai_gen/internal/data/chapter"
	"novels_ai_gen/internal/data/character"
	"novels_ai_gen/internal/data/event"
	"novels_ai_gen/internal/data/novel"
	novelagent2 "novels_ai_gen/internal/data/novelagent"
	"novels_ai_gen/internal/data/novelsummary"
	"novels_ai_gen/internal/data/objectstore"
	"novels_ai_gen/internal/data/prompt"
	"novels_ai_gen/internal/data/relationship"
	"novels_ai_gen/internal/server"
)

import (
	_ "novels_ai_gen/docs"
)

// Injectors from wire.go:

// initializeApp 使用 Wire 生成应用依赖图。
// 参数 configFile 表示实际配置文件路径。
func initializeApp(configFile string) (*server.App, func(), error) {
	configManager, cleanup, err := config.NewManager(configFile)
	if err != nil {
		return nil, nil, err
	}
	appConfig := config.CurrentConfig(configManager)
	slogLogger, cleanup2, err := logger.Provider(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	service := auth.NewService(configManager)
	handler := auth2.NewHandler(service)
	gormDB, cleanup3, err := db.Provider(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repository := novel.NewRepository(gormDB)
	novelService := novel2.NewService(repository)
	novelHandler := novel3.NewHandler(novelService)
	chapterRepository := chapter.NewRepository(gormDB)
	chapterService := chapter2.NewService(chapterRepository)
	chapterHandler := chapter3.NewHandler(chapterService)
	characterRepository := character.NewRepository(gormDB)
	characterService := character2.NewService(characterRepository)
	characterHandler := character3.NewHandler(characterService)
	relationshipRepository := relationship.NewRepository(gormDB)
	relationshipService := relationship2.NewService(relationshipRepository)
	relationshipHandler := relationship3.NewHandler(relationshipService)
	eventRepository := event.NewRepository(gormDB)
	eventService := event2.NewService(eventRepository)
	eventHandler := event3.NewHandler(eventService)
	aiproviderRepository := aiprovider.NewRepository(gormDB)
	cipher, err := aiprovider2.NewCipher(appConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	modelClient := aiprovider2.NewModelClient()
	aiproviderService := aiprovider2.NewService(aiproviderRepository, cipher, modelClient)
	aiproviderHandler := aiprovider3.NewHandler(aiproviderService)
	novelsummaryRepository := novelsummary.NewRepository(gormDB)
	einoAgentRuntimeFactory := novelagent.NewEinoAgentRuntimeFactory(chapterRepository, novelsummaryRepository)
	novelagentRepository := novelagent2.NewRepository(gormDB)
	novelagentService := novelagent.NewService(aiproviderRepository, cipher, configManager, einoAgentRuntimeFactory, novelagentRepository)
	novelagentHandler := novelagent3.NewHandler(novelagentService)
	novelsummaryService := novelsummary2.NewService(novelsummaryRepository)
	novelsummaryHandler := novelsummary3.NewHandler(novelsummaryService)
	promptRepository := prompt.NewRepository(gormDB)
	promptService := prompt2.NewService(promptRepository, configManager)
	promptHandler := prompt3.NewHandler(promptService)
	client, err := objectstore.NewClient(appConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uploadService := upload.NewService(appConfig, client)
	uploadHandler := upload2.NewHandler(uploadService)
	configHandler := config2.NewHandler(configManager)
	logHandler := log.NewHandler(configManager)
	systemService := system.NewService()
	systemHandler := system2.NewHandler(systemService)
	engine := router.NewRouter(handler, novelHandler, chapterHandler, characterHandler, relationshipHandler, eventHandler, aiproviderHandler, novelagentHandler, novelsummaryHandler, promptHandler, uploadHandler, configHandler, logHandler, systemHandler, service)
	httpServer := server.NewHTTPServer(appConfig, engine)
	app := server.NewApp(slogLogger, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
