// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	auth2 "novels_ai_gen/internal/api/handler/auth"
	chapter3 "novels_ai_gen/internal/api/handler/chapter"
	character3 "novels_ai_gen/internal/api/handler/character"
	config2 "novels_ai_gen/internal/api/handler/config"
	novel3 "novels_ai_gen/internal/api/handler/novel"
	relationship3 "novels_ai_gen/internal/api/handler/relationship"
	upload2 "novels_ai_gen/internal/api/handler/upload"
	"novels_ai_gen/internal/api/router"
	"novels_ai_gen/internal/biz/auth"
	chapter2 "novels_ai_gen/internal/biz/chapter"
	character2 "novels_ai_gen/internal/biz/character"
	novel2 "novels_ai_gen/internal/biz/novel"
	relationship2 "novels_ai_gen/internal/biz/relationship"
	"novels_ai_gen/internal/biz/upload"
	"novels_ai_gen/internal/bootstrap/config"
	"novels_ai_gen/internal/bootstrap/db"
	"novels_ai_gen/internal/bootstrap/logger"
	"novels_ai_gen/internal/data/chapter"
	"novels_ai_gen/internal/data/character"
	"novels_ai_gen/internal/data/novel"
	"novels_ai_gen/internal/data/objectstore"
	"novels_ai_gen/internal/data/relationship"
	"novels_ai_gen/internal/server"
)

import (
	_ "novels_ai_gen/docs"
)

// Injectors from wire.go:

// initializeApp 使用 Wire 生成应用依赖图。
// 参数 configFile 表示实际配置文件路径。
func initializeApp(configFile string) (*server.App, func(), error) {
	configManager, cleanup, err := config.NewManager(configFile)
	if err != nil {
		return nil, nil, err
	}
	appConfig := config.CurrentConfig(configManager)
	slogLogger, cleanup2, err := logger.Provider(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	service := auth.NewService(configManager)
	handler := auth2.NewHandler(service)
	gormDB, cleanup3, err := db.Provider(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repository := novel.NewRepository(gormDB)
	novelService := novel2.NewService(repository)
	novelHandler := novel3.NewHandler(novelService)
	chapterRepository := chapter.NewRepository(gormDB)
	chapterService := chapter2.NewService(chapterRepository)
	chapterHandler := chapter3.NewHandler(chapterService)
	characterRepository := character.NewRepository(gormDB)
	characterService := character2.NewService(characterRepository)
	characterHandler := character3.NewHandler(characterService)
	relationshipRepository := relationship.NewRepository(gormDB)
	relationshipService := relationship2.NewService(relationshipRepository)
	relationshipHandler := relationship3.NewHandler(relationshipService)
	client, err := objectstore.NewClient(appConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uploadService := upload.NewService(appConfig, client)
	uploadHandler := upload2.NewHandler(uploadService)
	configHandler := config2.NewHandler(configManager)
	engine := router.NewRouter(handler, novelHandler, chapterHandler, characterHandler, relationshipHandler, uploadHandler, configHandler, service)
	httpServer := server.NewHTTPServer(appConfig, engine)
	app := server.NewApp(slogLogger, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
