// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	auth2 "novels_ai_gen/internal/api/handler/auth"
	novel3 "novels_ai_gen/internal/api/handler/novel"
	upload2 "novels_ai_gen/internal/api/handler/upload"
	"novels_ai_gen/internal/api/router"
	"novels_ai_gen/internal/biz/auth"
	novel2 "novels_ai_gen/internal/biz/novel"
	"novels_ai_gen/internal/biz/upload"
	"novels_ai_gen/internal/bootstrap/config"
	"novels_ai_gen/internal/bootstrap/db"
	"novels_ai_gen/internal/bootstrap/logger"
	"novels_ai_gen/internal/data/novel"
	"novels_ai_gen/internal/data/objectstore"
	"novels_ai_gen/internal/server"
)

import (
	_ "novels_ai_gen/docs"
)

// Injectors from wire.go:

// initializeApp 使用 Wire 生成应用依赖图。
// 参数 configFile 表示实际配置文件路径。
func initializeApp(configFile string) (*server.App, func(), error) {
	appConfig, err := config.Load(configFile)
	if err != nil {
		return nil, nil, err
	}
	slogLogger, cleanup, err := logger.Provider(appConfig)
	if err != nil {
		return nil, nil, err
	}
	service := auth.NewService(appConfig)
	handler := auth2.NewHandler(service)
	gormDB, cleanup2, err := db.Provider(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repository := novel.NewRepository(gormDB)
	novelService := novel2.NewService(repository)
	novelHandler := novel3.NewHandler(novelService)
	client, err := objectstore.NewClient(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uploadService := upload.NewService(appConfig, client)
	uploadHandler := upload2.NewHandler(uploadService)
	engine := router.NewRouter(handler, novelHandler, uploadHandler, service)
	httpServer := server.NewHTTPServer(appConfig, engine)
	app := server.NewApp(slogLogger, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
