CREATE TABLE IF NOT EXISTS novels (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '小说主键ID',
  name VARCHAR(255) NOT NULL COMMENT '小说名，不能为空',
  author_name VARCHAR(255) NULL COMMENT '作者名，可以为空',
  description TEXT NULL COMMENT '简介，可以为空',
  tags VARCHAR(1000) NULL COMMENT '标签，可以为空，多个标签使用英文逗号分隔',
  cover_url VARCHAR(1000) NULL COMMENT '封面链接，可以为空',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='小说信息表';
